### ISSUE TITLE
Support `ko` as builder?

### ISSUE THREAD

**Issue by embano1** [knative/func#1477]
Has there been any discuss around supporting [`ko`](https://github.com/ko-build/ko) as a builder for Go based funcs?

```yaml
build:
  buildpacks:
  - paketo-buildpacks/go-dist
  - ghcr.io/boson-project/go-function-buildpack:tip
  builder: pack
  buildEnvs: []
```

```go
// Builder is the name of the subsystem that will complete the underlying
// build (pack, s2i, etc)
Builder string `yaml:"builder" jsonschema:"enum=pack,enum=s2i"`
```
