### ISSUE TITLE
Not able to specify autoscaling options

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1481]
Function can't be deployed, if autoscaling options are specified in `func.yaml`. 

```yaml
deploy:
  namespace: default
  remote: false
  annotations: {}
  options:
    scale:
      min: 1
      max: 10
```
then: 
```bash
func deploy
   🙌 Function image built: myregistry/default/myfunc:latest
🕘 ⬆️  Deploying function to the cluster
Error: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid key name "autoscaling.knative.dev/max-scale": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
invalid key name "autoscaling.knative.dev/min-scale": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
```
