### ISSUE TITLE
Unable to build `pack` images that don't also have `s2i` builders when `s2i` is the default

### ISSUE THREAD

**Issue by tvand** [knative/func#1492]
According to the [Release Notes](https://docs.openshift.com/dedicated/serverless/serverless-release-notes.html#serverless-rn-1-26_serverless-release-notes), Openshift Serverless Operator 1.26 comes with kn 1.5.0 and kn func plugin 1.8.1.

With these versions
`kn func create --language node` 
creates a func.yaml that uses a different specification version (previous was 0.25.0):
```
specVersion: 0.34.0
name: kn-1-5-0
runtime: node
registry: ""
image: ""
imageDigest: ""
created: 2023-01-11T16:41:50.0787175+01:00
invocation:
  format: http
build:
  buildpacks: []
  builder: ""
  buildEnvs: []
run:
  volumes: []
  envs: []
deploy:
  namespace: ""
  annotations: {}
  options: {}
  labels: []
  healthEndpoints:
    liveness: /health/liveness
    readiness: /health/readiness
```
This format is not covered by the [reference documentation](https://github.com/knative/func/blob/knative-v1.8.1/docs/reference/func_yaml.md) AFAICS.

Where can I find the current documentation?
