### ISSUE TITLE
func.yaml - shouldn't be `build.remote` instead of `deploy.remote` ?

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1515]
The `remote` property that marks remote (on cluster) build is located in `deploy` in func.yaml, shouldn't it be in `build` section, where it makes more sense?

ie:
```
name: test-function
runtime: node
build:
  buildpacks: []
  builder: pack
  buildEnvs:
run:
  volumes: []
  envs: []
deploy:
  namespace: demo
  remote: false            # <-- originally here
  annotations: {}
  options: {}
  labels: []
```
->

```
name: test-function
runtime: node
build:
  buildpacks: []
  builder: pack
  buildEnvs:
  remote: false           # <-- move here
run: 
  volumes: []
  envs: []
deploy:
  namespace: demo
  annotations: {}
  options: {}
  labels: []
```
