### ISSUE TITLE
Higher level event routing per function

### ISSUE THREAD

**Issue by matzew** [knative/func#1522]
Having a OrderService, that has two method for his functionality
* accept payment (and verification)
* complete order after delivery has been dispatched (to the door)

This could result in code like:

```java
    @Funq
    public CloudEvent<PaymentReceived> function(CloudEvent<?> newOrderRequest) {
        try {
            PaymentReceived payment = paymentProvider.processPayment(newOrderRequest.data());
            return CloudEventBuilder.create().build(payment);
        } catch (InvalidPaymentException ipe) {
            // recover from here
            return null;
        }
    }

    @Funq
    public CloudEvent<OrderCompleted> function(CloudEvent<OrderDispatched> orderDispatched) {

        orderService.updateOrderState(orderDispatched);

        return CloudEventBuilder.create().build(...);
    }
```

Now, currently it not possible to route "CloudEvents", based on their type/attributes (etc), to the specific `@Funq` method?

Like:

```java
    @Funq
    @CEInput(type = "order.requested")
    public CloudEvent<PaymentReceived> function(CloudEvent<?> newOrderRequest)
...
```

This could than also result in generating the trigger, using `CESQL`, like:

```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: my-service-trigger
spec:
  broker: default
  filters:
    - cesql: "type IN ('order.requested', 'order.dispatched')"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-service
```
