### ISSUE TITLE
Annotations removed from `func.yaml` are not removed from deployed function

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1571]
1. Deploy function with this func.yaml:
```yaml
  annotations:
    foo: bar
    xxx: zzz
```
2. KSVC with deployed function has both annotations  `foo: bar` and  `xxx: zzz` set
3. Remove `xxx: zzz` from func.yaml and redeploy
```yaml
  annotations:
    foo: bar
```
4. KSVC with deployed function has still both annotations  `foo: bar` and  `xxx: zzz` set
