### ISSUE TITLE
Support PVC and emptyDir in `run.volumes` in func.yaml

### ISSUE THREAD

**Issue by zalsader** [knative/func#1647]
## Description

Currently, in func.yaml, you can create volumes from a secret or a configmap using:

```yaml
...
run:
  volumes:
    - secret: "my-secret"
      path: "/secret"
    - configMap: "my-config-map"
      path: "/config"
...
```

It would be nice if other volume types are supported. For example, knative has a [feature where a PVC](https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-persistentvolumeclaim-pvc) can be used to create a volume, and another where an [empty dir](https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-emptydir-volume) could be used. This could be achieved by adding more options to the volumes map:

```
...
run:
  volumes:
    - presistentVolumeClaim: "my-pvc"
      path: "/pvc"
    - emptyDir: {}
      path: "/emptydir"
...
```

## Why this is helpful?

Currently, the only way to do this is to deploy the function then edit the resulting service.serving.knative.dev as described in [the features docs](https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-emptydir-volume). It would be more seamless if the volumes could be specified in the func.yaml directly.
