### ISSUE TITLE
Allow dynamic creation of PVCs mounted as volumes

### ISSUE THREAD

**Issue by rabejens** [knative/func#1759]
With the newest version of `func` built from the `main` branch here it is possible to mount PVCs when correctly given in the `func.yaml` like:

```yaml
run:
  volumes:
  - persistentVolumeClaim:
      claimName: foo
    path: /foo
```

It would be nice if it was also possible to have this PVC created / a fitting volume requested if it does not exist. For this, there should be options like `storageClassName`, `size` and maybe some selector like:

```yaml
run:
  volumes:
  - persistentVolumeClaim:
      claimName: foo
      storageClassName: mystorageclass
      size: "1Gi"
      persist: true
    path: /foo
```

or:

```yaml
run:
  volumes:
  - persistentVolumeClaim:
      claimName: foo
      persist: false
      selector:
        matchLabels:
          foo.bar: moo
    path: /foo
```

I know ephemeral storage could be mounted using `emptyDir`, but I created a language pack, builder and buildpacks that make it possible to run stuff on [Apache Spark](https://spark.apache.org) and when running this on Kubernetes, the container starts several other containers and they all need to share a directory they use to exchange data. This is usually done by using a RWX PVC the function container and all the driver and executor pods mount at the same place in their file system.

The `persist` option should, if set to `false`, delete a dynamically-created PVC if it did not exist before.
