### ISSUE TITLE
Renaming of BuildEnvs

### ISSUE THREAD

**Issue by lkingland** [knative/func#1818]
the Function struct's BuildEnvs member should be renamed simply "Envs" (along with its yaml serialized name).

The reasoning for this is not just because it is redundant, but because it is a hint to people manually editing the `func.yaml` that it should be defined at the wrong level.  for example, if you only look at the names of the members, it would be logical to assume the correct `func.yaml` structure to be:
```yaml
build:
  pvcSize: 256Mi
buildEnvs:
 - name: MY_ENV
    value: myvalue
```
When in reality the correct structure is the unnecessarily redundant
```
build:
  pvcSize: 256Mi
  buildEnvs:
  - name: MY_ENV
    value: myvalue
```

(see [Slack question](https://cloud-native.slack.com/archives/C04LKEZUXEE/p1686932247775899))
