### ISSUE TITLE
Double quotes in func.yaml overwritten with single quotes

### ISSUE THREAD

**Issue by nettrino** [knative/func#2056]
Hello all, 

I have a func.yaml which accesses secrets like so:
```yaml
specVersion: 0.35.0
...
invoke: cloudevent
build:
  builder: pack
run:
  envs:
    - name: GITHUB_APP_ID
      value: "{{ secret:github-app-id:GITHUB_APP_ID }}"
    - name: GITHUB_APP_PRIVATE_KEY
      value: "{{ secret:github-app-private-key:GITHUB_APP_PRIVATE_KEY }}"
...
```

Upon running `kn func deploy --build`, `func.yaml` is being overwritten and double quotes are replaced with single quotes, and as a result the env variables are not fetched dynamically as they should but interpreted as fixed strings.
