### ISSUE TITLE
func describe ignores extensions on the trigger

### ISSUE THREAD

**Issue by matzew** [knative/func#2077]
Doing `func subscribe` for a few attributes/extensions, like:

```bash
func subscribe --filter type=com.example --filter extension=my-extension-value --source my-broker
```
Results in the correct trigger:

```yaml
...
  spec:
    broker: my-broker
    filter:
      attributes:
        extension: my-extension-value
        type: com.example
    subscriber:
...
```

However, `func describe` is not showing the extensions:

```bash
func describe
Function name:
  app4
Function is built in image:
  
Function is deployed in namespace:
  default
Routes:
  http://app4.default.svc.cluster.local
Subscriptions (Source, Type, Broker):
   com.example my-broker
```

Should we enhance this a bit, since we now are able to create subscriptions (aka Triggers)?
