### ISSUE TITLE
Install package with apt during `func build`

### ISSUE THREAD

**Issue by tommazzo89** [knative/func#2128]
Hi everyone,

I'm working on a face detection function in Python, which I generated using `kn func -l python` and which uses the `opencv-pyton` package. When I build and deploy the function (using `kn func build` and `kn func deploy`), the deployment fails and I get a long error message from the function's startup. The essence of the error is the following:

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Apparently I need to install the `libgl1` OS package to fix this error. How can I install a package using the `apt` package manager during `kn func build`?

I tried adding the [dmikusa/apt-buildpack](https://github.com/dmikusa/apt-buildpack) to `func.yaml`. The build completes, but the other buildpacks seem to be gone, e.g., there is no CPython layer in the final image. This is my `func.yaml`

```YAML
specVersion: 0.35.0
name: detect-faces
runtime: python
registry: polarissloc
image: polarissloc/chunk-func-detect-faces:latest
created: 2024-01-19T17:05:13.540623154+01:00
build:
  builder: pack
  buildpacks:
    ## I tried it with and without the commented out buildpacks.
    # - gcr.io/paketo-buildpacks/ca-certificates:3.6.3
    - ghcr.io/dmikusa/buildpacks/dmikusa_apt:0.0.2
    # - gcr.io/paketo-buildpacks/watchexec:2.8.3
    # - gcr.io/paketo-buildpacks/cpython:1.9.0
    # - gcr.io/paketo-buildpacks/pip:0.18.0
    # - gcr.io/paketo-buildpacks/pip-install:0.6.0
    # - gcr.io/paketo-buildpacks/python-start:0.14.14
    # - gcr.io/paketo-buildpacks/procfile:5.6.4
  buildEnvs:
  - name: BP_CPYTHON_VERSION
    value: 3.11.*
deploy:
  namespace: func-test
```

I also tried adding the default Python buildpacks to `func.yaml`, which I extracted from a verbose build log. Then, I get the following errors:
```
===> DETECTING
Timer: Detector started at 2024-01-20T20:42:59Z
Checking for match against descriptor: {linux amd64  [{ubuntu 18.04}]}
======== Output: dmikusa/apt@0.0.2 ========
Apt
======== Results ========
pass: paketo-buildpacks/ca-certificates@3.6.3
pass: dmikusa/apt@0.0.2
pass: paketo-buildpacks/watchexec@2.8.3
pass: paketo-buildpacks/cpython@1.9.0
pass: paketo-buildpacks/pip@0.18.0
pass: paketo-buildpacks/pip-install@0.6.0
pass: paketo-buildpacks/python-start@0.14.14
pass: paketo-buildpacks/procfile@5.6.4
Resolving plan... (try #1)
fail: paketo-buildpacks/ca-certificates@3.6.3 provides unused ca-certificates
Resolving plan... (try #2)
fail: paketo-buildpacks/python-start@0.14.14 requires conda-environment
Resolving plan... (try #3)
fail: paketo-buildpacks/python-start@0.14.14 requires poetry
Resolving plan... (try #4)
fail: paketo-buildpacks/pip-install@0.6.0 provides unused site-packages
Resolving plan... (try #5)
fail: paketo-buildpacks/watchexec@2.8.3 provides unused watchexec
Resolving plan... (try #6)
fail: paketo-buildpacks/python-start@0.14.14 requires conda-environment
Resolving plan... (try #7)
fail: paketo-buildpacks/python-start@0.14.14 requires poetry
Resolving plan... (try #8)
fail: paketo-buildpacks/pip-install@0.6.0 provides unused site-packages
Timer: Detector ran for 61.324115ms and ended at 2024-01-20T20:42:59Z
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
Error: executing lifecycle: failed with status code: 20
Error: exit status 1
```

Does anybody have an idea how to install an OS package using `apt`, either using the buildpack that I mentioned or in some other way?

My installed software versions are:
- kn: v1.12.0
- kn func plugin: v0.38.0-99-gcd0bc6a

**Comment by lkingland** [comment]
Hello @tommazzo89,

Thank you for opening the issue!  This unfortunately may not be too easy at this time.

The first thing you might try is to use the "full" builder, which may already include the library you're looking for.  This can be specified with the flag `--builder-image=http://ghcr.io/knative/builder-jammy-full`.  If not, then since the installation of a package via apt is a privileged operation, you might want to look into creating a builder image which includes the library, and specify that during build with `--builder-image=[your builder]` flag.  Your builder could be based on one of the buildpack images, but with the library you're looking for installed.  However, this may not be sufficient because the runtime image rquires the library as well, which would mean building the runtime image using the 'pack' CLI.

Please feel free to join us in the CNCF Slack channel `#knative-functions`!

**Comment by matejvasek** [comment]
@tommazzo89 could you try it without the watchdog bp?

**Comment by matejvasek** [comment]
To me it appears gcr.io/paketo-buildpacks/watchexec:2.8.3 breaks the detection.

**Comment by matejvasek** [comment]
```sh
cat Aptfile 
freeglut3-dev
libglib2.0-0
```
```yaml
build:
  buildpacks:
  - ghcr.io/dmikusa/buildpacks/dmikusa_apt:0.0.2
  - gcr.io/paketo-buildpacks/ca-certificates:3.6.3
  - gcr.io/paketo-buildpacks/cpython:1.9.0
  - gcr.io/paketo-buildpacks/pip:0.18.0
  - gcr.io/paketo-buildpacks/pip-install:0.6.0
  - gcr.io/paketo-buildpacks/python-start:0.14.14
  - gcr.io/paketo-buildpacks/procfile:5.6.4
```
This should work @tommazzo89
