### ISSUE TITLE
deploy error: knative deployer failed to wait for the Knative Service to become ready: timeout: service

### ISSUE THREAD

**Issue by Vishal1297** [knative/func#2233]
Hi am facing an error while deploying service on k8s having http server.
Health check api's keeps hitting the endpoint even before the server start.
How should I configure timeout?

func deploy -v
**Error:**
```
deploy error: knative deployer failed to wait for the Knative Service to become ready: timeout: service 'kn-go-func' not ready after 120 seconds
Error: knative deployer failed to wait for the Knative Service to become ready: timeout: service 'kn-go-func' not ready after 120 seconds
```

**func.yaml**
```
specVersion: 0.35.0
name: kn-go-func
runtime: go
registry: private.artifactory.com/docker-dev/vishal-test-images
image: private.artifactory.com/docker-dev/vishal-test-images/kn-go-func:0.0.1
created: 2024-03-12T18:21:14.1444738+05:30
build:
  buildpacks:
  - paketo-buildpacks/go
  - paketo-buildpacks/go-mod-vendor
  builder: pack
  buildEnvs:
  - name: BP_GO_VERSION
    value: "1.21"
  - name: SSL_CERT_DIR
    value: /workspace
  - name: BP_KEEP_FILES
    value: '*/*'
  - name: BP_LOG_LEVEL
    value: DEBUG
deploy:
  namespace: default
  healthEndpoints:
    liveness: /actuator/health
    readiness: /actuator/health
```
