### ISSUE TITLE
Regarding the issues of compilation and deployment. knative 1.14

### ISSUE THREAD

**Issue by Taylorzhao** [knative/func#2331]
When deploying with func deploy, there is a func.yaml file under the directory, and parameters such as the deployed image have already been described in the file. However, when deploying, it does not read the image in the func.yaml, but reads the image of build-image under.func. When I delete the.func directory under the directory, the deployment will report an error, as shown in the figure.
<img width="1130" alt="image" src="https://github.com/knative/func/assets/13677508/06494414-2e32-42d6-9feb-e32c2674fa07">
However, in versions 1.12 and earlier of Knative, this issue did not exist.
A simple deployment method should only require one yaml file to be sufficient.

my fun.yaml.
```yaml
specVersion: 0.36.0
name: instantiate
runtime: go
registry: 192.168.100.167:80
image: 192.168.100.167:80/serverless/flow-model-gvcbkl-instantiate:v3
namespace: flow-model-gvcbkl
created: 2024-05-28T10:39:25.562440871Z
build:
  builder: pack
run:
  envs:
  - name: FUNC_ID
    value: 5fd83203-aeaf-48c8-88d2-7fa3fc07aa90
  - name: FUNC_TYPE
    value: http
  - name: FUNC_NAME
    value: instantiate
deploy:
  namespace: flow-model-gvcbkl
  image: 192.168.100.167:80/serverless/flow-model-gvcbkl-instantiate:v3
  options:
    scale:
      min: 1
      max: 5
      metric: concurrency
      target: 75
      utilization: 75
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
        concurrency: 100
```

There is still one question. In the.func directory, in the built-hash and built-image files, there are only the corresponding string contents, but there is execution permission. The file permission should be read-only.
