### ISSUE TITLE
Redundant and confusing labels added by default

### ISSUE THREAD

**Issue by rhuss** [knative/func#2565]
When deploying a function, I get a KService with the following metadata:

```
metadata:
  annotations:
    dapr.io/app-id: demo
    dapr.io/app-port: "8080"
    dapr.io/enable-api-logging: "true"
    dapr.io/enabled: "true"
    dapr.io/metrics-port: "9092"
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/lastModifier: kubernetes-admin
  labels:
    boson.dev/function: "true"
    boson.dev/runtime: quarkus
    function.knative.dev: "true"
    function.knative.dev/name: demo
    function.knative.dev/runtime: quarkus
```

This is quite noisy and adds a (soft) dependency on Dapr, which I would not add by default. It is confusing for people not using Dapr to see such annotations on their services unconditionally.

My proposal:

* Make adding the `dapr.io` annotations optional and enable them only when a Dapr installation is detected or configured by the user.
* Remove the `boson.dev` annotations, they are redundant
* Remove `function.knative.dev` as it is redundant and adds some noise. You can always check for the existence of `function.knative.dev/name` like with `kubectl get pods -l function.knative.dev/name`. Removing that `function.knative.dev` annotation would avoid inconsistencies when it is set but the `name` is not (like when manually edited).
