### ISSUE TITLE
Support multiple triggers on kn-subscribe

### ISSUE THREAD

**Issue by matzew** [knative/func#2572]
Running `func subscribe --filter type=org.apache.camel.event.aws.s3.getObject --filter type=org.apache.camel.event.aws.sqs.getObject` should result in two triggers, and not just one.

```
cat func.yaml

specVersion: 0.36.0
name: wjaxs3-logger
runtime: go
created: 2024-11-05T14:06:23.457899513+01:00
invoke: cloudevent
deploy:
  subscriptions:
  - source: default
    filters:
      type: org.apache.camel.event.aws.sqs.getObject
```
