### ISSUE TITLE
Mounting volumes with different permissions is not possible

### ISSUE THREAD

**Issue by guygordon** [knative/func#2642]
I was trying to use the func utility for deploying a function with and noticed that I can't set anywhere the default mode of any volume.

It would be great if I could set volume mode in func.yaml file for deploying functions.

**Comment by lkingland** [comment]
Hello @guygordon,

We expose a subset of options through the Functions abstraction.  While we are steadily expanding the set of options available through this abstraction, you can unlock the full power of Knative Services (including this setting) by using `func build` to create your container, followed by deploying the container using a Knative Service with this option set.  For exampe:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-service
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: [Image Created from `func build`
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: my-config
          defaultMode: 0644
```
Please join us on the Slack channel if you have other problems, or just to let us know it worked out for you.
