### ISSUE TITLE
'func deploy --remote' fail with Python 3.11 and Python 3.12

### ISSUE THREAD

**Issue by vvarga007** [knative/func#2829]
I am trying to deploy a Knative function using Python 3.11 or 3.12, and the deployment steps fail.

func.yaml
```yaml
specVersion: 0.36.0
name: func-test
runtime: python
registry: artifactory.xxx.xxx
image: xxx.xx.dev/xxxx/knative-func-test
namespace: default
created: 2025-04-24T16:13:35.799733-04:00
build:
  git:
    url: https://xxx:GITHUBTOKENGOESHERE@xxx.xxxx.dev/xxx/xxxx.git
    revision: master
    contextDir: func-test
  builder: pack
  buildEnvs:
    - name: BP_CPYTHON_VERSION
      value: "3.12.*"
    - name: BP_IMAGE_LABELS
      value: 'io.packeto.example="Adding Custom Labels"'
deploy:
  namespace: default
  image: xxxxx.xxxx.xxx/xxxx/knative-func-test
  options:
    scale:
      min: 1
      max: 10
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
        concurrency: 100
```

All the steps are working fine, except the deploy step.
The error message I get:

ERROR: cannot load function: Error: 
Migration: cannot deserialize old sub-structure: EOF

**Comment by matejvasek** [comment]
@vvarga007 does it work with different versions of Python?

**Comment by matejvasek** [comment]
How did you created the function? When? What version of func CLI did you use?

**Comment by matejvasek** [comment]
btw today you need to use builder `s2i`, the `pack` builder is broken today.

**Comment by matejvasek** [comment]
```
func version -v
func environment
```

**Comment by matejvasek** [comment]
I also would suggest removing
```yaml
  git:
    url: https://xxx:GITHUBTOKENGOESHERE@xxx.xxxx.dev/xxx/xxxx.git
    revision: master
    contextDir: func-test
````
part and use "direct upload".
