### ISSUE TITLE
Autoconfigure knative serving domains

### ISSUE THREAD

**Issue by lkingland** [knative/func#47]
In order to support a new domain name (TLD+1) on the Kubernetes provider, the `config-domain` ConfigMap currentl has to be manually updated by the cluster administrator:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  # Must manually add one entry per TLD+1:
  example.com: |
    selector:
      faas.domain: "example.com"
  example.org: |
    selector:
      faas.domain: "example.org"
  # Default is local only.
  svc.cluster.local: ""
```
This could be automated by augmenting the function `Create` step to alter this list.
