### ISSUE TITLE
On-cluster build: Implement `--git` flag for `func deploy`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/func#765]
- If the user uses `func deploy --git <GIT_REPO>`
  - the `func.yaml` will automatically set build to `git` and specify the git repository

In other words, I will be defaulting the following information to avoid manually editing `func.yaml`: 

```
build: git                                          # required, specify `git` build type
git:
  url: https://github.com/my-repo/my-function.git   # required, git repository with the function source code
  revision: main                                    # optional, git revision to be used (branch, tag, commit)
  # contextDir: myfunction                          # optional, needed only if the function is not located
                                                    # in the repository root folder
```

I will update this issue if I find more details and consequences of using `--git`
