### ISSUE TITLE
Document and reference Github Actions for building and deploying func projects

### ISSUE THREAD

**Issue by salaboy** [knative/func#982]
Building and Deploying functions can be performed purely by Github actions, without the need for any other tools. 
This process needs to be documented and explained in the docs for people to be able to setup their repositories with these actions.

**Comment by salaboy** [comment]
@thomasvitale is already working on implementing some GitHub actions workflows here: 

https://github.com/ThomasVitale/kn-func-build

**Comment by ThomasVitale** [comment]
The work on the GitHub action is still in progress. In the meantime, this is an example of building and pushing an image using the func CLI explicitly in a GitHub Actions workflow: https://github.com/ThomasVitale/devoxxuk-question-1/blob/main/.github/workflows/commit-stage.yml#L72

**Comment by salaboy** [comment]
@ThomasVitale I am really interested in your idea of creating a native action with Typescript, can you paste here some links to some references about what you had in mind? 
If we start with something simple for just building and publishing the function artifacts to ghcr it will be great.

**Comment by ThomasVitale** [comment]
@salaboy After a few experiments, I came up with a possible solution for having support for `func` in GitHub Actions. And the TypeScript option gives the most flexibility there.

A first action would be something like **`func-setup-action`** for installing the `func` CLI and make it available on the current runner. By default, it would install the latest version, but an optional parameter could be used to install a specific version. After that, it would be possible to use the `func` CLI directly.

```yaml
steps:
    - uses: knative/func-setup-action@v1
    - run: func version
```

For convenience, it could be useful to have some specialised actions for some of the operations provided by `func`, like **`func-build-action`** and **`func-deploy-action`**.

```yaml
steps:
    - uses: knative/func-setup-action@v1
    - uses: knative/func-build-action@v1
       with:
           path: .
           publish: true
           name: spring-boot-func
           version: 3.9.4
```

The prerequisite for using any of those actions would be to have the runner already authenticated with a container registry, for example using the `docker/login-action` or `redhat-actions/podman-login`.
